title: Mike
description: Mike's Personal Blog
author: Mike
logo: /static/img/avatar.png
github: https://github.com/mikezone
about: Leisure Nerd

# baseurl: "/" # now is ""
# url: "https://mikezone.github.io"
url: "http://mikezh.com"

disqus_shortname: Mike
# google_analytics: UA-72862926-1

# share:
#   twitter_username: \#
#   fb_appid: 000000000000

permalink: /:year/:month/:title/
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, jekyll-archives]

# Tag
enableTags: true
tagarray: []

# paginate
paginate: 10
per_page: 10
paginate_path: "/page/:num/"

# directory
include: ["misc"]
show_dir_listing: true

# jekyll-archives:
#   enabled: all
#   enabled:
#     - categories
#   enabled:
#     - year
#     - month
#     - tags
#   layout: 'posts_by_category'
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     day: '/:year/:month/:day/'
#     tag: '/tag/:name/'
#     category: '/category/:name/'

# derectory_listing
directory_listing_title: "Contents: "
directory_listing_prefix: "Contents of "