title: Mike
description: My Personal Blog
author: Mike
logo: /static/img/avatar.png
github: https://github.com/mikezone
about: Leisure Nerd

baseurl: "/"
url: ""

disqus_shortname: Mike
# google_analytics: UA-72862926-1

# share:
#   twitter_username: \#
#   fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
